# Generated by Django 2.2.11 on 2020-03-21 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='¿Cual es tu correo electrónico?'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^(\\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}$', 'Añade un número de teléfono válido.')], verbose_name='¿Cual es tu número de teléfono?'),
        ),
    ]
