# Generated by Django 2.2.11 on 2020-03-24 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_importar_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAccesoColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='¿Cual es tu nombre?')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(\\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}$', 'Añade un número de teléfono válido.')], verbose_name='¿Cual es tu número de teléfono?')),
                ('email', models.EmailField(max_length=254, verbose_name='¿Cual es tu correo electrónico?')),
                ('mensaje', models.TextField(verbose_name='Indica brevemente como podrían ayudarte:')),
                ('acceso_permitido', models.BooleanField(default=False)),
                ('codigo_acceso', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Colaborador')),
            ],
            options={
                'verbose_name': 'Solicitud de Colaborador',
                'verbose_name_plural': 'Solicitudes de colaborador',
            },
        ),
    ]
