# Generated by Django 2.2.11 on 2020-03-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_solicitudaccesocolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaccesocolaborador',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_acceso', to='colaboradores.Colaborador'),
        ),
    ]
