# Generated by Django 2.2.11 on 2020-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_related_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudaccesocolaborador',
            options={'verbose_name': 'Solicitud de acceso', 'verbose_name_plural': 'Solicitudes de acceso'},
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='servicios',
            new_name='mensaje',
        ),
        migrations.AlterField(
            model_name='solicitudaccesocolaborador',
            name='mensaje',
            field=models.TextField(verbose_name='¿Qué necesitas?'),
        ),
    ]
