# Generated by Django 2.2.11 on 2020-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_editar_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudaccesocolaborador',
            options={'verbose_name': 'Petición de ayuda', 'verbose_name_plural': 'Peticiones de ayuda'},
        ),
    ]
