# Generated by Django 2.2.12 on 2020-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0012_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fuente',
            field=models.CharField(default='???', max_length=25),
        ),
        migrations.AddField(
            model_name='solicitudaccesocolaborador',
            name='fuente',
            field=models.CharField(default='???', max_length=25),
        ),
    ]
