# Generated by Django 2.2.11 on 2020-03-18 12:45

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nombre', models.CharField(max_length=500, verbose_name='¿Cual es tu nombre?')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(\\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}$', 'Añade un número de teléfono válido.')], verbose_name='¿Cual es tu número de teléfono?')),
                ('email', models.EmailField(max_length=254, verbose_name='¿Cual es tu correo electrónico?')),
                ('peticion', models.TextField(help_text='Indica qué necesitas')),
            ],
            options={
                'verbose_name': 'Petición',
                'verbose_name_plural': 'Peticiones',
            },
        ),
    ]
