# Generated by Django 2.2.11 on 2020-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0007_editar_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudaccesopeticion',
            options={'verbose_name': 'Oferta de colaboración', 'verbose_name_plural': 'Ofertas de colaboración'},
        ),
    ]
