# Generated by Django 2.2.11 on 2020-03-31 10:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0009_actualizada_validacion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='solicitudaccesopeticion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='¿Cual es tu correo electrónico?'),
        ),
        migrations.AlterField(
            model_name='solicitudaccesopeticion',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
