# Generated by Django 2.2.11 on 2020-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0011_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
    ]
