# Generated by Django 2.2.12 on 2020-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0012_peticion_atendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='fuente',
            field=models.CharField(default='???', max_length=25),
        ),
        migrations.AddField(
            model_name='solicitudaccesopeticion',
            name='fuente',
            field=models.CharField(default='???', max_length=25),
        ),
    ]
