# Generated by Django 2.2.11 on 2020-03-28 11:27

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('fuente', models.CharField(max_length=500)),
                ('accion', models.CharField(max_length=500)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
    ]
