# Generated by Django 2.2.11 on 2020-03-30 12:49

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre del comercio')),
                ('telefono', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^(\\+34|0034|34)?[ -]*(6|7|9)[ -]*([0-9][ -]*){8}$', 'Añade un número de teléfono válido.')], verbose_name='Número de teléfono')),
                ('mensaje', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
            },
        ),
    ]
