# Generated by Django 2.2.11 on 2020-03-31 11:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
