# Generated by Django 2.2.11 on 2020-03-31 11:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0002_actualizado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Por defecto acepta números españoles. Para añadir un número extranjero, añade el prefijo internacional', max_length=128, region=None),
        ),
    ]
