# Generated by Django 2.2.12 on 2020-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='fuente',
            field=models.CharField(default='???', max_length=25),
        ),
    ]
